[package]
name = "init_clan"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "init_clan"

[dependencies]
bolt-lang = { version = "0.1.0", features = ["cpi"] }
clan = { path = "../../components/clan" }
player_profile = { path = "../../components/player_profile" }

