version: 2
updates:
  # Backend dependencies (Rust/Cargo)
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend)"

  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(frontend)"
    groups:
      # Group Solana packages
      solana:
        patterns:
          - "@solana/*"
      # Group React packages
      react:
        patterns:
          - "react*"
          - "@types/react*"
      # Group dev dependencies
      dev-dependencies:
        dependency-type: "development"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"

