[package]
name = "player_profile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "player_profile"

[dependencies]
bolt-lang = { version = "0.1.0", features = ["cpi"] }

